# Generated by Django 6.0.4 on 2026-04-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='address',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='registration',
            name='MobileNo',
            field=models.IntegerField(),
        ),
    ]
